---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cs2-pvc
  namespace: cs2ns
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: do-block-storage-retain

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cs2-cm
  namespace: cs2ns
data:
   TZ: Asia/Singapore
   DEFAULT_WORKSPACE: /config/workspace
   PROXY_DOMAIN: code2-139.59.223.165.nip.io

---
apiVersion: v1
kind: Secret
metadata:
  name: cs2-secret
  namespace: cs2ns
type: Opaque
data:
  PASSWORD: cGFzc3dvcmQ=
  SUDO_PASSWORD: cGFzc3dvcmQ=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cs2-deploy
  namespace: cs2ns
  labels:
    app: cs2
    name: cs2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs2
      name: cs2-po
  template:
    metadata:
      name: cs2-po
      labels:
        app: cs2
        name: cs2-po    
    spec:
      volumes:
      - name: cs2-data-vol
        persistentVolumeClaim:
          claimName: cs2-pvc
      containers:
      - name: cs2-container
        image: linuxserver/code-server:amd64-4.22.0
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: cs2-data-vol
          mountPath: /config/workspace
        ports:
        - name: cs2-web-port
          containerPort: 8443       
        envFrom:
        - configMapRef:
            name: cs2-cm
        - secretRef:
            name: cs2-secret             

---
apiVersion: v1
kind: Service
metadata:
  name: cs2-svc
  namespace: cs2ns
  labels:
    app: cs2
    name: cs2-svc  
spec:
  type: ClusterIP
  selector:
    app: cs2
    name: cs2-po
  ports:
  - name: cs2-svc-port
    port: 8443
    targetPort: cs2-web-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cs2-ing
  namespace: cs2ns
  labels:
    app: cs2
    name: cs2-ing 
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "https://$host/oauth2/auth"
    nginx.ingress.kubernetes.io/auth-signin: "https://$host/oauth2/start?rd=$escaped_request_uri"
spec:
  ingressClassName: nginx
  rules:
  - host: code2-139.59.223.165.nip.io
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: cs2-svc
            port:
              name: cs2-svc-port