---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth2-deploy
  namespace: cs2ns
  labels:
    app: cs2
    name: oauth2-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cs2
      name: oauth2-po
  template:
    metadata:
      name: oauth2-po
      labels:
        app: cs2
        name: oauth2-po    
    spec:
      containers:
      - name: oauth2-container
        image: bitnami/oauth2-proxy:7.2.1
        imagePullPolicy: IfNotPresent
        ports:
        - name: oauth2-port
          containerPort: 4180
        args:
        - --provider=github        
        - --email-domain=*
        - --upstream=file:///dev/null
        - --http-address=0.0.0.0:4180
        - --cookie-secret=uKrFWqXhUiP6Pj2UqZb43WXZeCRLrZm0
        - --client-id=8b4d4a8970357de8328d
        - --client-secret=2215a1efee5df827aa496f1756cc56e8fdb0b881

---
apiVersion: v1
kind: Service
metadata:
  name: oauth2-svc
  namespace: cs2ns
  labels:
    app: cs2
    name: oauth2-svc  
spec:
  type: ClusterIP
  selector:
    app: cs2
    name: oauth2-po
  ports:
  - name: oauth2-svc-port
    port: 4180
    targetPort: oauth2-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oauth2-ing
  namespace: cs2ns
  labels:
    app: cs2
    name: oauth2-ing
spec:
  ingressClassName: nginx
  rules:
  - host: code2-139.59.223.165.nip.io
    http: 
      paths:
      - path: /oauth2
        pathType: Prefix
        backend: 
          service:
            name: oauth2-svc
            port:
              name: oauth2-svc-port