---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bgg
      name: bggapp-po
  template:
    metadata:
      name: bggapp-po
      labels:
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v2
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: bggapp-cm
        - secretRef:
            name: bggapp-secret
        ports:
        - name: web-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: web-port
          periodSeconds: 30
          initialDelaySeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: web-port
          periodSeconds: 30
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 50m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi            

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: bggapp-cm
  namespace: bggns
data:
   BGG_DB_USER: root
   BGG_DB_HOST: bggdb-svc.bggns.svc.cluster.local

---
apiVersion: v1
kind: Secret
metadata:
  name: bggapp-secret
  namespace: bggns
type: Opaque
data:
  BGG_DB_PASSWORD: Y2hhbmdlaXQ=

---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  #type: ClusterIP
  #type: NodePort
  type: ClusterIP
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - name: bggapp-web-port
    port: 3000
    targetPort: web-port

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bggapp-ing
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-ing
spec:
  ingressClassName: nginx
  rules:
  - host: bgg-139.59.223.165.nip.io
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: bggapp-svc
            port:
              name: bggapp-web-port

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bggapp-hpa
  namespace: bggns
spec:
  minReplicas: 1
  maxReplicas: 6
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bggapp-deploy
  metrics:
  - type: Resource
    resource: 
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource: 
      name: memory
      target:
        type: Utilization
        averageUtilization: 80