---
apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
  namespace: minio-ns
type: Opaque
data:
  MINIO_ROOT_USER: YWRtaW4=
  MINIO_ROOT_PASSWORD: cGFzc3dvcmQxMjM=

---
apiVersion: v1
kind: Service
metadata:
  name: minio-hsvc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-hsvc  
spec:
  clusterIP: None
  selector:
    app: minio
    name: minio-sts-po
  ports:
  - name: hsvc-data-port
    port: 9000
    targetPort: data-port
  - name: hsvc-web-port
    port: 9090
    targetPort: web-port

---
apiVersion: v1
kind: Service
metadata:
  name: minio-svc
  namespace: minio-ns
  labels:
    app: minio
    name: minio-svc  
spec:
  type: ClusterIP
  selector:
    app: minio
    name: minio-sts-po
  ports:
  - name: svc-data-port
    port: 9000
    targetPort: data-port
  - name: svc-web-port
    port: 9090
    targetPort: web-port  


---
apiVersion: v1
kind: ConfigMap
metadata:
  name: minio-cm
  namespace: minio-ns
data:
  MINIO_CI_CD: "1"
#   MINIO_DISTRIBUTED_MODE_ENABLED: "yes"
#   MINIO_DISTRIBUTED_NODES: minio-sts-{0...3}.minio-hsvc.minio-ns.svc.cluster.local/data
#   MINIO_SKIP_CLIENT: "yes"

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio-sts
  namespace: minio-ns
spec:
  serviceName: minio-hsvc
  replicas: 4
  selector:
    matchLabels:
      app: minio
      name: minio-sts-po
  volumeClaimTemplates:
  - apiVersion: apps/v1
    kind: PersistentVolumeClaim
    metadata:
      name: minio-data-vol
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: do-block-storage-retain
      resources:
        requests:
          storage: 1Gi      
  template:
    metadata:
      name: minio-sts-po
      labels:
        app: minio
        name: minio-sts-po
    spec:
    #  initContainers:
    #  - name: minio-init
    #    image: busybox
    #    imagePullPolicy: IfNotPresent
    #    command:
    #    - /bin/sh
    #    - -c
    #    - "chown 1001:1001 /opt/data"
    #    volumeMounts:
    #    - name: minio-data-vol
    #      mountPath: /data        
      containers:
      - name: minio-sts-container
        image: bitnami/minio:2024.3.10
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: minio-data-vol
          mountPath: /opt/data
        ports:
        - name: data-port
          containerPort: 9000
        - name: web-port
          containerPort: 9090
        - name: health-port
          containerPort: 900
        envFrom:
        - secretRef:
            name: minio-secret
        - configMapRef:
            name: minio-cm         
        livenessProbe:
          httpGet:
            path: /minio/health/live
            port: health-port
          periodSeconds: 30
          initialDelaySeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 250Mi
          requests:
            cpu: 40m
            memory: 50Mi
        command: #exec
        - minio
        - server
        - --address=:9000
        - --console-address=:9090
        - minio-sts-{0...3}.minio-hsvc.minio-ns.svc.cluster.local/opt/data
#        readinessProbe:
#          httpGet:
#            path: /minio/health/ready
#            port: health-port
#          periodSeconds: 30
#          initialDelaySeconds: 5

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ing
  namespace: minio-ns
  labels:
    app: minio
    name: minio-ing
spec:
  ingressClassName: nginx
  rules:
  # - host: data-139.59.223.165.nip.io
  #   http: 
  #     paths:
  #     - path: /
  #       pathType: Prefix
  #       backend: 
  #         service:
  #           name: minio-svc
  #           port:
  #             name: data-port
  - host: console-139.59.223.165.nip.io
    http: 
      paths:
      - path: /
        pathType: Prefix
        backend: 
          service:
            name: minio-svc
            port:
              name: svc-web-port